{% set name = "sz" %}
{% set version = "v2.1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/szcompressor/SZ/archive/{{ version }}.tar.gz
  sha256: e4f8ad8f4cb232b7bc20cd2924a2a338495119123c21018b91af9e1ffe3fb94d 

build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - zlib
    - zstd
  run:
    - zlib
    - zstd

about:
  home: https://robertu94.github.io/libpressio
  license: BSD-3-Clause
  license_family: BSD
  license_file: copyright-and-BSD-license.txt
  summary: 'SZ: Error-bounded lossy Compressor for HPC data'
  description: |
     new error-controlled lossy compression algorithm for large-scale
     scientific data, based on pointwise error bounds as opposed to
     absolute error bounds. Significantly improves the prediction hitting
     rate (or prediction accuracy) for each data point while greatly
     reducing data size.
  doc_url: https://github.com/szcompressor/SZ
  dev_url: https://github.com/szcompressor/SZ

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
